### ISSUE TITLE
File field uploads with CF Pro error

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2295]
If a file field is in form -- I don't think it's every configuration, I have to figure that out still, when CF Pro API client creates an instance of a \Caldera_Forms_Entry, $entry_id is null, so nothing works.

https://github.com/CalderaWP/Caldera-Forms/blob/master/includes/cf-pro-client/classes/api/message.php#L190

**Comment by Shelob9** [comment]
[08-Feb-2018 02:23:32 UTC] PHP Fatal error:  Uncaught Error: Call to a member function to_array() on null in /app/wp-content/plugins/caldera-forms/includes/cf-pro-client/classes/api/message.php:190
Stack trace:
#0 /app/wp-content/plugins/caldera-forms/includes/cf-pro-client/classes/send.php(82): calderawp\calderaforms\pro\api\message->add_entry_data(NULL, Array)
#1 /app/wp-content/plugins/caldera-forms/includes/cf-pro-client/classes/hooks.php(100): calderawp\calderaforms\pro\send::main_mailer(Array, NULL, 'CF5a592725305bf', true)
#2 /app/wp/wp-includes/class-wp-hook.php(286): calderawp\calderaforms\pro\hooks->mailer(Array, Array, Array, NULL)
#3 /app/wp/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#4 /app/wp-content/plugins/caldera-forms/classes/save.php(421): apply_filters('caldera_forms_m...', Array, Array, Array, NULL)
#5 /app/wp-content/plugins/caldera-forms/classes/core.php(843): Caldera_Forms_Save_Final::do_mailer(Array, NULL)
#6 /app/wp/wp-includes/class-wp-hook.php(288): Caldera_Forms->save_final_form(Array)
#7 /app/wp/wp-in in /app/wp-content/plugins/caldera-forms/includes/cf-pro-client/classes/api/message.php on line 190

**Comment by Shelob9** [comment]
That error is fixed in PR #2297 which isn't merged yet, but should get merged into this fix as well. But that doesn't fix actual issue that for some fucking reason $entry_id is null. I must know why but also I'm tired AF.

**Comment by Shelob9** [comment]
Possibly related error on user site `PHP Notice:  Undefined index: default in`~/plugins/caldera-forms-pro/includes/calcdefaults.php on line 50`

**Comment by Shelob9** [comment]
PR #2343  is for this.

**Comment by Shelob9** [comment]
Close via 2885ba8 PR #2343
