### ISSUE TITLE
PHP error in DeleteFileJob

### ISSUE THREAD

**Issue by ictbeheer** [CalderaWP/Caldera-Forms#3340]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.3PHP Version: 7.2.22MySQL Version: 5.6.45Caldera Forms Version: 1.8.7WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When CF tries to delete a file that was uploaded in a form a PHP error is thrown.

## What PHP Errors Have You Logged While Reproducing This Bug?
```
ErrorException: dirname() expects parameter 1 to be string, array given
#9 wp-content/plugins/caldera-forms/cf2/Jobs/DeleteFileJob.php(78): handleError
#8 wp-content/plugins/wp-sentry-integration/vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): dirname
#7 wp-content/plugins/caldera-forms/cf2/Jobs/DeleteFileJob.php(78): dirName
#6 wp-content/plugins/caldera-forms/cf2/Jobs/DeleteFileJob.php(45): handle
#5 wp-content/plugins/caldera-forms/vendor/a5hleyrich/wp-queue/src/WP_Queue/Worker.php(47): process
#4 wp-content/plugins/caldera-forms/vendor/a5hleyrich/wp-queue/src/WP_Queue/Cron.php(105): cron_worker
#3 wp-includes/class-wp-hook.php(286): apply_filters
#2 wp-includes/class-wp-hook.php(310): do_action
#1 wp-includes/plugin.php(531): do_action_ref_array
#0 wp-cron.php(133): null
```

## Cause
Caldera_Forms_Files::schedule_delete() is called with the wrong parameters:

https://github.com/CalderaWP/Caldera-Forms/blob/ff614a4bd16381f92d6314a0d2f907f4951938d2/classes/files.php#L57

https://github.com/CalderaWP/Caldera-Forms/blob/ff614a4bd16381f92d6314a0d2f907f4951938d2/classes/files.php#L414

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by hannesdorn** [comment]
wp-content/plugins/caldera-forms/classes/files.php:
`public static function schedule_delete($field_id, $form_id, $file )
caldera_forms_schedule_job(new \calderawp\calderaforms\cf2\Jobs\DeleteFileJob($file));`
$file is an array...

wp-content/plugins/caldera-forms/cf2/Jobs/DeleteFileJob.php:
`__construct($path)`
$path is an array with file, url and type

wp-content/plugins/caldera-forms/cf2/Jobs/DeleteFileJob.php:
`function dirName()
{
	return dirname($this->path);
}`
-> throws an exception.

-> this would fix it:
wp-content/plugins/caldera-forms/cf2/Jobs/DeleteFileJob.php:
`public function __construct($path)
{
    if (is_array($path)) {
        $this->path = $path['file'];
    } else {
        $this->path = $path;
    }
}`
