### ISSUE TITLE
PHP 8 Fatal Error

### ISSUE THREAD

**Issue by riverBanjo** [CalderaWP/Caldera-Forms#3679]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress 5.6 
* Caldera Forms 1.9.4
* PHP 8.0

## What PHP Errors Have You Logged While Reproducing This Bug?

> Warning: require(C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\symfony\polyfill-mbstring/bootstrap80.php): Failed to open stream: No such file or directory in C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\symfony\polyfill-mbstring\bootstrap.php on line 15
> 
> Fatal error: Uncaught Error: Failed opening required 'C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\symfony\polyfill-mbstring/bootstrap80.php' (include_path='.;C:\php\pear') in C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\symfony\polyfill-mbstring\bootstrap.php:15 Stack trace: #0 C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\composer\autoload_real.php(69): require() #1 C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\composer\autoload_real.php(59): composerRequireb6656ff7e1a4bf56611bfebfbafb5265('0e6d7bf4a5811bf...', 'C:\\wamp64\\www\\w...') #2 C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\autoload.php(7): ComposerAutoloaderInitb6656ff7e1a4bf56611bfebfbafb5265::getLoader() #3 C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\caldera-core.php(113): include_once('C:\\wamp64\\www\\w...') #4 C:\wamp64\www\wordpress-5.6\wordpress\wp-includes\class-wp-hook.php(287): caldera_forms_load('') #5 C:\wamp64\www\wordpress-5.6\wordpress\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #6 C:\wamp64\www\wordpress-5.6\wordpress\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #7 C:\wamp64\www\wordpress-5.6\wordpress\wp-settings.php(420): do_action('plugins_loaded') #8 C:\wamp64\www\wordpress-5.6\wordpress\wp-config.php(90): require_once('C:\\wamp64\\www\\w...') #9 C:\wamp64\www\wordpress-5.6\wordpress\wp-load.php(37): require_once('C:\\wamp64\\www\\w...') #10 C:\wamp64\www\wordpress-5.6\wordpress\wp-admin\admin.php(34): require_once('C:\\wamp64\\www\\w...') #11 C:\wamp64\www\wordpress-5.6\wordpress\wp-admin\index.php(10): require_once('C:\\wamp64\\www\\w...') #12 {main} thrown in C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\symfony\polyfill-mbstring\bootstrap.php on line 15

**Comment by Much2tall** [comment]
> Warning: require(C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\symfony\polyfill-mbstring**/**bootstrap80.php): Failed to open stream: No such file or directory in C:\wamp64\www\wordpress-5.6\wordpress\wp-content\plugins\caldera-forms\vendor\symfony\polyfill-mbstring**\**bootstrap.php on line 15

One of these things is not like the other.

**Comment by spitzlbergerj** [comment]
Same Problem here.
In version 1.9.4 there is a query in the file .../wp-content/plugins/caldera-forms/vendor/symfony/polyfill-mbstring/bootstrap.php for php8 . If php8 is used, a file bootstrap80.php is expected. This is not included in the 1.9.4 version. I just checked the website and downloaded the zip of version 1.9.4. The file bootstrap80.php is not included there either.

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000014737807

This user is experiencing this issue.

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000014738327

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000014765029

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000014918821

**Comment by New0** [comment]
@riverBanjo Could you share that beta with PHP8 users - https://github.com/CalderaWP/Caldera-Forms/releases/download/1.9.5-b1/1.9.5-b1.zip - and let us know if that it fixes this issue?

**Comment by riverBanjo** [comment]
@New0 yes.

**Comment by riverBanjo** [comment]
@New0 I've given every ticket mentioned in this issue a link to the beta. If I run across more users experiencing this issue I will give them the beta and mention their ticket here.

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000015360259

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000015363313

**Comment by riverBanjo** [comment]
@New0 Just an update, it looks like this is solving the issue and have continued to give it to users.

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000015155546

**Comment by spitzlbergerj** [comment]
Hi, the beta solves the issue for me

**Comment by riverBanjo** [comment]
https://desk.zoho.com/support/saturdaydriveinc/ShowHomePage.do#Cases/dv/413570000016476037

**Comment by spitzlbergerj** [comment]
Hi @riverBanjo,
unfortunately I don't have a zoho account. Therefore I can not read the linked post. Can you please post here what is described there. Thanks!
Regards
Sepp

**Comment by riverBanjo** [comment]
@spitzlbergerj 

> @New0 I've given every ticket mentioned in this issue a link to the beta. If I run across more users experiencing this issue I will give them the beta and mention their ticket here.

**Comment by New0** [comment]
> I am hitting this issue now, can you provide me with a link to the beta

@LaurieY the link to the beta is mentioned above in the discussion - [https://github.com/CalderaWP/Caldera-Forms/releases/download/1.9.5-b1/1.9.5-b1.zip](https://github.com/CalderaWP/Caldera-Forms/releases/download/1.9.5-b1/1.9.5-b1.zip) -

**Comment by faithangelu** [comment]
Hello. I used this but for some reason, the import and new form button isn't working. 

> > I am hitting this issue now, can you provide me with a link to the beta
> 
> @LaurieY the link to the beta is mentioned above in the discussion - https://github.com/CalderaWP/Caldera-Forms/releases/download/1.9.5-b1/1.9.5-b1.zip -
